[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_staking = "F5XkWN1H23Axp34UgZkymELSVKLkXBRzTHq8QmUsggCo"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn ts-node client/*.ts"
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
